name: lwrcl_dart
description: Dart FFI bindings for lwrcl (Lightweight rclcpp compatible library).
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ffi: ^2.0.0
